### ISSUE TITLE
Container fails to start when run with command in readme

### ISSUE THREAD

**Issue by endoze** [luzifer-docker/mumble#1]
When I attempted to fire up this container for the first time based on the readme command `docker run -d -p 64738:64738 luzifer/mumble`, I get an error of `readdirent: not a directory`.

![screen shot 2015-01-26 at 9 40 09 am](https://cloud.githubusercontent.com/assets/997161/5901291/62a08b2e-a53f-11e4-990f-f265c8b8fa8f.png)

I believe this is a result of [this line](https://github.com/luzifer-docker/mumble/blob/4e654768d6bf33c46724f9211aa3ea696c3a2e1b/Dockerfile#L9) in the Dockerfile.
 Shouldn't the second argument be a directory and not a file? I was under the impression that volumes needed to be directories and not files. Is this not the case?

**Comment by artibyrd** [comment]
endoze is correct, I believe this is an issue as of Docker v 1.6 allowing only directories and not files to be mounted as volumes in the dockerfile.  This looks like a Docker bug as an equivalent CLI command works fine.

https://github.com/docker/compose/issues/424

**Comment by Luzifer** [comment]
Container should be fixed with 747497d (please pay attention, this changes the mount point for config)
